[package]
name = "dll"
version = "0.1.0"
edition = "2021"
# Practice repo; no publishing!
publish = false
# Using Affero to scare away people from copying this for themselves, as they
# should:
#  a) use a better crate; or,
#  b) write it themselves ;)
license = "AGPL-3.0-or-later"

[dependencies]
